name: .NET Core

on: [push]

jobs:
  build:
    strategy:
      matrix:
        dotnet: [ '3.1.200' ]
        os: [ubuntu-latest, ubuntu-16.04, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - ${{ matrix.dotnet }}
    
    steps:
    - name: Getting context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
      
    - name: Getting code
      uses: actions/checkout@v1
      
    - name: Getting Nuget cache
      if: runner.os == 'When the cache will be faster'
      uses: actions/cache@v1
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget
          
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    
    - name: Build
      run: dotnet build --configuration Release --nologo
    
    - name: Run tests
      run: dotnet test --configuration Release --nologo
      if: runner.os == 'Windows' &&
          matrix.dotnet == '3.1.100' 
